sudo: required
services:
  - docker

before_install:
  - docker build -t rbramos/react-app -f Dockerfile.dev .

script:
  - docker run rbramos/react-app npm run test -- --coverage

#deploy:
#  provider: elasticbeanstalk
#  region: "eu-east-1"
#  app: "react-app"
#  env: "React-app-env"
#  bucket_name: ""
#  bucket_path: ""
#  on:
#    branch: master
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key:
#    secure: $AWS_SECRET_KEY
