language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t rbramos/react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true rbramos/react-app npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "react-app"
  env: "ReactApp-env"
  bucket_name: "elasticbeanstalk-eu-west-1-066840243337"
  bucket_path: "react-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
